"""GAT — a decision-focused, uncertainty-aware BIM state engine.

    Design intent + evidence + criteria -> auditable architectural belief
        -> decision or next evidence -> propagated, verified state
"""

from gat.adapters.openusd import (
    DEFAULT_OPENUSD_READ_LIMITS,
    OPENUSD_CARRIER_FORMAT,
    OPENUSD_CARRIER_VERSION,
    OPENUSD_SIGNATURE_ALGORITHM,
    OPENUSD_SUPPORTED_VERSIONS,
    OpenUsdKeyPair,
    OpenUsdLoadResult,
    OpenUsdMigrationReport,
    OpenUsdReadLimits,
    OpenUsdSignatureInfo,
    generate_openusd_keypair,
    migrate_openusd,
    openusd_available,
    read_openusd,
    write_openusd,
)
from gat.engine.executor import ExecutionResult, World, execute
from gat.engine.dynamics import (
    EvolveLinearGaussian,
    ProcessForecastStep,
    ProcessRollout,
    forecast_process,
)
from gat.causal import (
    ApprovalDecision,
    ApprovalRecord,
    AssessmentRecord,
    ExternalActionRecord,
    ExternalActionStatus,
    PolicyRecord,
    clearance_assessment_record,
    clearance_policy_record,
    decision_assessment_record,
    decision_policy_record,
    decode_causal_record,
    encode_causal_record,
)
from gat.engine.active_inference import (
    MinimumPreference,
    ObservationCandidate,
    ObservationPlan,
    plan_observations,
    select_observation,
)
from gat.engine.decision import (
    DecisionAssessment,
    DecisionEvidencePlan,
    DecisionVerdict,
    EvidenceDisposition,
    MinimumDecision,
    assess_decision,
    plan_decision_evidence,
)
from gat.engine.transform import (
    CompositeTransformation,
    Measurement,
    ObservationTransformation,
    ObserveLinearized,
    ObserveQuantity,
    ScaleParameter,
    SetParameter,
    ShiftParameter,
    Transformation,
)
from gat.engine.verify import VerificationReport, run_invariants
from gat.errors import (
    GatError,
    LedgerError,
    LikelihoodCalibrationError,
    LoweringError,
    NumericalError,
    OpenUsdError,
    SnapshotError,
    SpfParseError,
    VerificationError,
)
from gat.ids import EntityId, VarId
from gat.ledger import (
    LEDGER_FORMAT,
    LEDGER_HASH_ALGORITHM,
    LEDGER_RUNTIME_CONTRACT,
    LEDGER_SCHEMA_VERSION,
    ExecutionLedger,
    LedgerEvent,
    LedgerReplayResult,
    decode_transformation,
    encode_transformation,
    read_ledger,
    replay_ledger,
    verification_digest,
    write_ledger,
)
from gat.session import GatSession
from gat.state_snapshot import (
    ComputationalEquivalenceReport,
    EquivalenceCheck,
    SnapshotLoadResult,
    capture_snapshot,
    computational_equivalence,
    read_snapshot,
    reconstruct_snapshot,
    write_snapshot,
)

__version__ = "0.1.0"

__all__ = [
    "ApprovalDecision",
    "ApprovalRecord",
    "assess_decision",
    "AssessmentRecord",
    "CompositeTransformation",
    "ComputationalEquivalenceReport",
    "DecisionAssessment",
    "DecisionEvidencePlan",
    "DecisionVerdict",
    "DEFAULT_OPENUSD_READ_LIMITS",
    "EntityId",
    "EquivalenceCheck",
    "ExecutionResult",
    "ExecutionLedger",
    "EvidenceDisposition",
    "EvolveLinearGaussian",
    "ExternalActionRecord",
    "ExternalActionStatus",
    "GatError",
    "GatSession",
    "LedgerError",
    "LedgerEvent",
    "LedgerReplayResult",
    "LEDGER_FORMAT",
    "LEDGER_HASH_ALGORITHM",
    "LEDGER_RUNTIME_CONTRACT",
    "LEDGER_SCHEMA_VERSION",
    "LikelihoodCalibrationError",
    "LoweringError",
    "MinimumDecision",
    "MinimumPreference",
    "Measurement",
    "NumericalError",
    "OpenUsdError",
    "OpenUsdKeyPair",
    "OpenUsdLoadResult",
    "OpenUsdMigrationReport",
    "OpenUsdReadLimits",
    "OpenUsdSignatureInfo",
    "OPENUSD_CARRIER_FORMAT",
    "OPENUSD_CARRIER_VERSION",
    "OPENUSD_SIGNATURE_ALGORITHM",
    "OPENUSD_SUPPORTED_VERSIONS",
    "ObservationCandidate",
    "ObservationPlan",
    "ObservationTransformation",
    "ObserveLinearized",
    "ObserveQuantity",
    "plan_decision_evidence",
    "plan_observations",
    "PolicyRecord",
    "ProcessForecastStep",
    "ProcessRollout",
    "openusd_available",
    "ScaleParameter",
    "select_observation",
    "SetParameter",
    "ShiftParameter",
    "SnapshotError",
    "SnapshotLoadResult",
    "SpfParseError",
    "Transformation",
    "VarId",
    "VerificationError",
    "VerificationReport",
    "World",
    "capture_snapshot",
    "computational_equivalence",
    "clearance_assessment_record",
    "clearance_policy_record",
    "decision_assessment_record",
    "decision_policy_record",
    "decode_causal_record",
    "decode_transformation",
    "encode_transformation",
    "encode_causal_record",
    "execute",
    "forecast_process",
    "generate_openusd_keypair",
    "migrate_openusd",
    "run_invariants",
    "read_openusd",
    "read_ledger",
    "read_snapshot",
    "reconstruct_snapshot",
    "replay_ledger",
    "write_snapshot",
    "write_ledger",
    "write_openusd",
    "verification_digest",
    "__version__",
]
